[package]
name = "lemmy_db_views_admin_block_instance_params"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true

[lib]
doctest = false

[lints]
workspace = true

[features]
full = ["ts-rs"]

[dependencies]
serde = { workspace = true }
ts-rs = { workspace = true, optional = true }
chrono = { workspace = true }
