[package]
name = "lemmy_db_views_follow_community"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true

[lib]
doctest = false

[lints]
workspace = true

[features]
full = ["ts-rs", "lemmy_db_schema/full"]

[dependencies]
lemmy_db_schema = { workspace = true }
serde = { workspace = true }
ts-rs = { workspace = true, optional = true }
