[package]
name = "lemmy_db_views_plugin_metadata"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true

[lib]
doctest = false

[lints]
workspace = true

[features]
full = [
  "ts-rs",
  "extism",
  "extism-convert"
]

[dependencies]
serde = { workspace = true }
ts-rs = { workspace = true, optional = true }
url = { workspace = true }
extism = { git = "https://github.com/extism/extism.git", branch = "pool", optional = true }
extism-convert = { git = "https://github.com/extism/extism.git", branch = "pool", optional = true }