[package]
name = "lemmy_db_views_my_user_info"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true

[lib]
doctest = false

[lints]
workspace = true

[features]
full = [
  "ts-rs",
  "lemmy_db_schema/full",
  "lemmy_db_views_local_user/full",
  "lemmy_db_views_community_follower/full",
  "lemmy_db_views_community_moderator/full",
]

[dependencies]
lemmy_db_schema = { workspace = true }
lemmy_db_views_local_user = { workspace = true }
lemmy_db_views_community_follower = { workspace = true }
lemmy_db_views_community_moderator = { workspace = true }
serde = { workspace = true }
ts-rs = { workspace = true, optional = true }
